[package]
name = "coin_launchpad"
version = "0.0.0"

[addresses]
std = "0x1"
initia_std = "0x1"

# use this when deploying
#launchpad_address = "0xB59FDAB462E531C85C72346AD722491A65DF3600"
# use this when testing
 launchpad_address = "_"

[dev-addresses]

# set to random address for testing
launchpad_address = "0x999"

[dependencies]
InitiaStdlib = { git = "https://github.com/initia-labs/move-natives", subdir = "initia_stdlib", rev = "main" }
